"""empty message

Revision ID: d1085e781aaa
Revises: 99c3fa8875f8
Create Date: 2024-05-29 13:17:53.230944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1085e781aaa'
down_revision = '99c3fa8875f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_owns',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('album_podcast_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['album_podcast_id'], ['albums_podcasts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'album_podcast_id')
    )
    op.drop_table('user_album_podcast')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_album_podcast',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('album_podcast_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['album_podcast_id'], ['albums_podcasts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'album_podcast_id')
    )
    op.drop_table('user_owns')
    # ### end Alembic commands ###
