"""empty message

Revision ID: 2f4ebab2762b
Revises: f1f1339d61e9
Create Date: 2024-05-29 19:18:00.159175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f4ebab2762b'
down_revision = 'f1f1339d61e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_owns')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_owns',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('album_podcast_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['album_podcast_id'], ['albums_podcasts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'album_podcast_id')
    )
    # ### end Alembic commands ###
