"""empty message

Revision ID: bcbbad79b1fa
Revises: 2f4ebab2762b
Create Date: 2024-05-29 19:18:50.663191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcbbad79b1fa'
down_revision = '2f4ebab2762b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_owns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('album_podcast_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['album_podcast_id'], ['albums_podcasts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_owns')
    # ### end Alembic commands ###
