"""empty message

Revision ID: e480781afc31
Revises: 4deb7e39c1f8
Create Date: 2024-05-30 18:37:45.346914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e480781afc31'
down_revision = '4deb7e39c1f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=60),
               existing_nullable=True)

    with op.batch_alter_table('songs_episodes', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.TIME(),
               type_=sa.String(length=8),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('firstname',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=40),
               existing_nullable=False)
        batch_op.alter_column('lastname',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=40),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('lastname',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=25),
               nullable=False)
        batch_op.alter_column('firstname',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=25),
               existing_nullable=False)

    with op.batch_alter_table('songs_episodes', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.String(length=8),
               type_=sa.TIME(),
               existing_nullable=True)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)

    # ### end Alembic commands ###
